<?php

/**
 * The file that defines the merchants attributes
 *
 * A class definition that includes attributes and functions used across the
 * admin area.
 *
 * @link       https://webappick.com/
 * @since      1.0.0
 *
 * @package    Woo_Feed
 * @subpackage Woo_Feed/includes
 * @author     Ohidul Islam <wahid@webappick.com>
 */

class Woo_Feed_Default_Attributes
{

    public $wooAttributes = array();


    public function __construct()
    {

    }

    public function merchants(){
        $merchants=array(
            "--1"               => "Feed Engine",
            "custom"            =>"Custom Feed",
            "---1"              => "",

            "--2"               =>"Feed Template",
            "google"            =>"Google Shopping",
            "adwords"           =>"Google Adword",
            "facebook"          =>"Facebook",
            "amazon"            =>"Amazon",
            "shopping"          =>"eBay (shopping.com)",
            "nextag"            =>"Nextag",
            "pricegrabber"      =>"Price Grabber",
            "kelkoo"            =>"Kelkoo",
            "shopzilla"         =>"Shopzilla",
            "shopmania"         =>"Shopmania",
            "shopbot"           =>"Shopbot",
            "bing"              =>"Bing",
            "become"            =>"Become",
            "connexity"         =>"Connexity",
            "---2"              => "",
        );
        return $merchants;
    }


    public function amazonAttributes(){
        $attributes=array(
            "--1"                            => "Required Fields",
            "Category"=>"Category",
            "Title"=>"Title",
            "Link"=>"Link",
            "SKU"=>"SKU",
            "Price"=>"Price",
            "Image"=>"Image",
            "---1"                           => "",
            "--2"                            => "Strongly Recommended Fields",
            "UPC"=>"UPC",
            "Brand"=>"Brand",
            "Recommended Browse Node"=>"Recommended Browse Node",
            "Department"=>"Department",
            "Description"=>"Description",
            "Manufacturer"=>"Manufacturer",
            "Mfr part number"=>"Mfr part number",
            "Shipping Cost"=>"Shipping Cost",
            "---2"                           => "",
            "--3"                            => "Recommended Fields",
            "Bullet point1"=>"Bullet point1",
            "Bullet point2"=>"Bullet point2",
            "Bullet point3"=>"Bullet point3",
            "Bullet point4"=>"Bullet point4",
            "Bullet point5"=>"Bullet point5",
            "Age"=>"Age",
            "Item package quantity"=>"Item package quantity",
            "Height"=>"Height",
            "Length"=>"Length",
            "Weight"=>"Weight",
            "Width"=>"Width",
            "Keywords1"=>"Keywords1",
            "Keywords2"=>"Keywords2",
            "Keywords3"=>"Keywords3",
            "Keywords4"=>"Keywords4",
            "Keywords5"=>"Keywords5",
            "Model Number"=>"Model Number",
            "Other image-url1"=>"Other image-url1",
            "Other image-url2"=>"Other image-url2",
            "Other image-url3"=>"Other image-url3",
            "Other image-url4"=>"Other image-url4",
            "Other image-url5"=>"Other image-url5",
            "Other image-url6"=>"Other image-url6",
            "Other image-url7"=>"Other image-url7",
            "Other image-url8"=>"Other image-url8",
            "Shipping Weight"=>"Shipping Weight",
            "Size"=>"Size",
            "Color"=>"Color",
            "Gender"=>"Gender",
            "Scent"=>"Scent",
            "Color and finish"=>"Color and finish",
            "Material"=>"Material",
            "Flavor"=>"Flavor",
            "Theme HPC"=>"Theme HPC",
            "League and Team"=>"League and Team",
            "Watch movement"=>"Watch movement",
            "Maximum age"=>"Maximum age",
            "Minimum age"=>"Minimum age",
            "Cuisine"=>"Cuisine",
            "Specialty"=>"Specialty",
            "Occasion"=>"Occasion",
            "Memory Card Type"=>"Memory Card Type",
            "Computer CPU speed"=>"Computer CPU speed",
            "Computer memory size"=>"Computer memory size",
            "Digital Camera Resolution"=>"Digital Camera Resolution",
            "Display size"=>"Display size",
            "Display technology"=>"Display technology",
            "Flash drive Size"=>"Flash drive Size",
            "Hard disk size"=>"Hard disk size",
            "Included RAM size"=>"Included RAM size",
            "Operating system"=>"Operating system",
            "Optical zoom"=>"Optical zoom",
            "Screen Resolution"=>"Screen Resolution",
            "Metal type"=>"Metal type",
            "Size per pearl"=>"Size per pearl",
            "Total Diamond Weight"=>"Total Diamond Weight",
            "Ring size"=>"Ring size",
            "Band material"=>"Band material",
            "---3"                           => "",
        );
    }

    public function googleAttributes()
    {
        $attributes = array(
            "--1"                            => "Basic Information",
            "id"                             => "Product Id[id]",
            "title"                          => "Product Title[title]",
            "description"                    => "Product Description[description]",
            "link"                           => "Product URL[link]",
            "mobile_link"                    => "Product URL[mobile_link]",
            "product_type"                   => "Product Categories[product_type] ",
            "current_category"               => "Google Product Category[google_product_category]",
            "image"                          => "Main Image[image_link]",
            "images_1"                       => "Additional Image 1 [additional_image_link]",
            "images_2"                       => "Additional Image 2 [additional_image_link]",
            "images_3"                       => "Additional Image 3 [additional_image_link]",
            "images_4"                       => "Additional Image 4 [additional_image_link]",
            "images_5"                       => "Additional Image 5 [additional_image_link]",
            "images_6"                       => "Additional Image 6 [additional_image_link]",
            "images_7"                       => "Additional Image 7 [additional_image_link]",
            "images_8"                       => "Additional Image 8 [additional_image_link]",
            "images_9"                       => "Additional Image 9 [additional_image_link]",
            "images_10"                      => "Additional Image 10 [additional_image_link]",
            "condition"                      => "Condition[condition]",
            "---1"                           => "",

            "--2"                            => "Availability & Price",
            "availability"                   => "Stock Status[availability]",
            "price"                          => "Regular Price[price]",
            "sale_price"                     => "Sale Price[sale_price]",
            "sale_price_effective_date"      => "Sale Price Effective Date[sale_price_effective_date]",
            "---2"                           => "",

            "--3"                            => "Unique Product Identifiers",
            "brand"                          => "Manufacturer[brand]",
            "upc"                            => "GTIN[gtin]",
            "sku"                            => "MPN[mpn]",
            "identifier_exists"              => "Identifier Exists[identifier_exists]",
            "---3"                           => "",

            "--4"                            =>"Detailed Product Attributes",
            "item_group_id"                  => "Item Group Id[item_group_id]",
            "color"                          => "Color[color]",
            "gender"                         => "Gender[gender]",
            "age_group"                      => "Age Group[age_group]",
            "material"                       => "Material[material]",
            "pattern"                        => "Pattern[pattern]",
            "size"                           => "Size of the item[size]",
            "size_type"                      => "Size Type[size_type]",
            "size_system"                    => "Size System[size_system]",
            "---4"                           => "",

            "--5"                            => "Tax & Shipping",
            "tax"                            => "Tax[tax]",
            "shipping_country"               => "Shipping Country",
            "shipping_service"               => "Shipping Service",
            "shipping_price"                 => "Shipping Price",
            "weight"                         => "Shipping Weight[shipping_weight]",
            "length"                         => "Shipping Length[shipping_length]",
            "width"                          => "Shipping Width[shipping_width]",
            "height"                         => "Shipping Height[shipping_height]",
            "shipping_label"                 => "Shipping Label[shipping_label]",
            "---5"                           => "",

            "--6"                            =>"Product Combinations",
            "multipack"                      => "Multipack[multipack]",
            "is_bundle"                      => "Is Bundle[is_bundle]",
            "---6"                           => "",

            "--7"                            => "Adult Products",
            "adult"                          => "Adult[adult]",
            "---7"                           => "",

            "--8"                            => "AdWord Attributes",
            "adwords_redirect"               => "Adwords Redirect[adwords_redirect]",
            "---8"                           => "",

            "--9"                             => "Custom Label Attributes",
            "custom_label_0"                  => "Custom label 0 [custom_label_0]",
            "custom_label_1"                  => "Custom label 1 [custom_label_1]",
            "custom_label_2"                  => "Custom label 2 [custom_label_2]",
            "custom_label_3"                  => "Custom label 3 [custom_label_3]",
            "custom_label_4"                  => "Custom label 4 [custom_label_4]",
            "---9"                            => "",

            "--10"                            => "Additional Attributes",
            "excluded_destination"            => "Excluded Destination[excluded_destination]",
            "expiration_date"                 => "Expiration Date [expiration_date]",
            "---10"                           => "",

            "--11"                            => "Unit Prices (EU Countries and Switzerland Only)",
            "unit_pricing_measure"            => "Unit Pricing Measure[unit_pricing_measure]",
            "unit_pricing_base_measure"       => "Unit Pricing Base Measure[unit_pricing_base_measure]",
            "---11"                           => "",

            "--12"                            => "Energy Labels",
            "energy_efficiency_class"         => "Energy Efficiency Class[energy_efficiency_class]",
            "---12"                           => "",

            "--13"                            => "Loyalty Points (Japan Only)",
            "loyalty_points"                  => "loyalty_points[loyalty_points]",
            "---13"                           => "",

            "--14"                            => "Multiple Installments (Brazil Only)",
            "installment"                     => "Installment[installment]",
            "---14"                           => "",

            "--15"                            => "Merchant Promotions Attribute",
            "promotion_id"                    => "Promotion Id[promotion_id]",
            "---15"                           => "",
        );

        return $attributes;
    }

    public function pricegrabberAttribute(){
        $attributes = array(
            "--1"                                   =>"Required Attributes",
            "Retsku"                                =>"Retsku",
            "Product Title"                         =>"Product Title",
            "Detailed Description"                  =>"Detailed Description",
            "Categorization"                        =>"Categorization",
            "Product URL"                           =>"Product URL",
            "Primary Image URL"                     =>"Primary Image URL",
            "Selling Price"                         =>"Selling Price",
            "Regular Price"                         =>"Regular Price",
            "Condition"                             =>"Condition",
            "Availability"                          =>"Availability",
            "Manufacturer Name"                     =>"Manufacturer Name",
            "GTIN"                                  =>"GTIN (UPC / EAN / ISBN)",
            "Mature"                                =>"Mature",
            "---1"                                  =>"",
            "--2"                                   =>"Additional Attributes",
            "Parent Retsku"                         =>"Parent Retsku",
            "Merchant Categorization"               =>"Merchant Categorization",
            "Manufacturer Part Number"              =>"Manufacturer Part Number",
            "Additional Image URL 1"                =>"Additional Image URL 1",
            "Additional Image URL 2"                =>"Additional Image URL 2",
            "Additional Image URL 3"                =>"Additional Image URL 3",
            "Additional Image URL 4"                =>"Additional Image URL 4",
            "Additional Image URL 5"                =>"Additional Image URL 5",
            "Additional Image URL 6"                =>"Additional Image URL 6",
            "Additional Image URL 7"                =>"Additional Image URL 7",
            "Additional Image URL 8"                =>"Additional Image URL 8",
            "Additional Image URL 9"                =>"Additional Image URL 9",
            "Additional Image URL 10"               =>"Additional Image URL 10",
            "Video URL"                             =>"Video URL",
            "Color"                                 =>"Color",
            "Size"                                  =>"Size",
            "Material"                              =>"Material",
            "Pattern"                               =>"Pattern",
            "Gender"                                =>"Gender",
            "Age"                                   =>"Age",
            "Parent UPC"                            =>"Parent UPC",
            "Multipack"                             =>"Multipack",
            "Shipping Cost"                         =>"Shipping Cost",
            "Weight"                                =>"Weight",
            "---2"                                  =>"",
        );
        return $attributes;
    }

    public function nextagAttribute(){
        $attributes=array(
            "--1"                                   => "Required Attributes",
            "Product Name"                          =>"Product Name",
            "Description"                           =>"Description",
            "Image URL"                             =>"Image URL",
            "Click-Out URL"                         =>"Click-Out URL",
            "Price"                                 =>"Price",
            "Category"                              =>"Category: Nextag Numeric ID or Other",
            "---1"                                  => "",
            "--2"                                   => "Additional Attributes",
            "Manufacturer"                          =>"Manufacturer",
            "Condition"                             =>"Condition",
            "Stock Status"                          =>"Stock Status",
            "Cost-per-Click "                       =>"Cost-per-Click ",
            "Distributor ID "                       =>"Distributor ID ",
            "Ground Shipping"                       =>"Ground Shipping",
            "Ingram Part #"                         =>"Ingram Part #",
            "ISBN"                                  =>"ISBN",
            "Manufacturer Part #"                   =>"Manufacturer Part #",
            "Marketing Message "                    =>"Marketing Message ",
            "MUZE ID"                               =>"MUZE ID",
            "Seller Part #"                         =>"Seller Part #",
            "UPC"                                   =>"UPC",
            "Weight"                                =>"Weight",
            "ListPrice"                             =>"ListPrice",
            "---2"                                  => "",
        );
        return $attributes;
    }

    public function kelkooAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "title"                                 =>"title",
            "product-url"                           =>"product-url",
            "price"                                 =>"price",
            "merchant-category"                     =>"merchant-category",
            "ean"                                   =>"ean",
            "delivery-cost"                         =>"delivery-cost",
            "brand"                                 =>"brand",
            "description"                           =>"description",
            "image-url"                             =>"image-url",
            "availability"                          =>"availability",
            "mpn"                                   =>"mpn",
            "---1"                                  =>"",
            "--2"                                   =>"Additional Attributes",
            "delivery-time"                         =>"delivery-time",
            "condition"                             =>"condition",
            "ecotax"                                =>"ecotax",
            "warranty"                              =>"warranty",
            "mobile-url"                            =>"mobile-url",
            "kelkoo-category-id"                    =>"kelkoo-category-id",
            "sku"                                   =>"sku",
            "colour"                                =>"colour",
            "unit-price"                            =>"unit-price",
            "offer-type"                            =>"offer-type",
            "merchant-info"                         =>"merchant-info",
            "currency"                              =>"currency",
            "image-url-2"                           =>"image-url-2",
            "image-url-3"                           =>"image-url-3",
            "image-url-4"                           =>"image-url-4",
            "green-product"                         =>"green-product",
            "green-label"                           =>"green-label",
            "sales-rank"                            =>"sales-rank",
            "unit-quantity"                         =>"unit-quantity",
            "made-in"                               =>"made-in",
            "occasion"                              =>"occasion",
            "efficiency-class"                      =>"efficiency-class",
            "shipping-method"                       =>"shipping-method",
            "delivery-cost-2"                       =>"delivery-cost-2",
            "shipping-method-2"                     =>"shipping-method-2",
            "delivery-cost-3"                       =>"delivery-cost-3",
            "shipping-method-3"                     =>"shipping-method-3",
            "delivery-cost-4"                       =>"delivery-cost-4  ",
            "shipping-method-4"                     =>"shipping-method-4",
            "zip-code"                              =>"zip-code",
            "stock-quantity"                        =>"stock-quantity",
            "shipping-weight"                       =>"shipping-weight",
            "payment-methods"                       =>"payment-methods",
            "voucher-title"                         =>"voucher-title",
            "voucher-description"                   =>"voucher-description",
            "voucher-url"                           =>"voucher-url",
            "voucher-code"                          =>"voucher-code",
            "voucher-start-date"                    =>"voucher-start-date",
            "voucher-end-date"                      =>"voucher-end-date",
            "price-no-rebate"                       =>"price-no-rebate",
            "percentage-promo"                       =>"percentage-promo",
            "promo-start-date"                      =>"promo-start-date",
            "promo-end-dat"                         =>"promo-end-dat",
            "user-rating"                           =>"user-rating",
            "nb-reviews"                            =>"nb-reviews",
            "user-review-link"                      =>"user-review-link",
            "video-link"                            =>"video-link",
            "video-title"                           =>"video-title",
            "---2"                                  =>"",
        );
        return $attributes;
    }

    public function shopzillaAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "Unique ID"                             =>"Unique ID",
            "Title"                                 =>"Title",
            "Description"                           =>"Description",
            "Category"                              =>"Category",
            "Product URL"                           =>"Product URL",
            "Image URL"                             =>"Image URL",
            "Condition"                             =>"Condition",
            "Availability"                          =>"Availability",
            "Current Price"                         =>"Current Price",
            "---1"                                  =>"",
            "--2"                                   =>"Recommended Attributes",
            "Brand"                                 =>"Brand",
            "GTIN"                                  =>"GTIN",
            "MPN"                                   =>"MPN",
            "Ship Cost"                             =>"Ship Cost",
            "Ship Weight"                           =>"Ship Weight",
            "Bid"                                   =>"Bid",
            "Regular Price"                         =>"Regular Price",
            "Promo Text"                            =>"Promo Text",
            "Gender"                                =>"Gender",
            "Age Group"                             =>"Age Group",
            "Color"                                 =>"Color",
            "Size"                                  =>"Size",
            "Material"                              =>"Material",
            "Pattern"                               =>"Pattern",
            "Item Group ID"                         =>"Item Group ID",
            "---2"                                  =>"",
            "--3"                                   =>"Optional Attributes",
            "Page ID"                               =>"Page ID",
            "Page ID Variant"                       =>"Page ID Variant",
            "Generic Title"                         =>"Generic Title",
            "Unit Price"                            =>"Unit Price",
            "Currency"                              =>"Currency",
            "PZN"                                   =>"PZN",
            "Adult"                                 =>"Adult",
            "Delivery Period"                       =>"Delivery Period",
            "Energy Efficiency Class"               =>"Energy Efficiency Class",
            "---3"                                  =>"",
        );
        return $attributes;
    }

    public function shoppingAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "Unique Merchant SKU"                   =>"Unique Merchant SKU",
            "Product Name"                          =>"Product Name",
            "Product URL"                           =>"Product URL",
            "Image URL"                             =>"Image URL",
            "Current Price"                         =>"Current Price",
            "Stock Availability"                    =>"Stock Availability",
            "Condition"                             =>"Condition",
            "MPN"                                   =>"MPN",
            "ISBN"                                  =>"ISBN",
            "UPC"                                   =>"UPC",
            "EAN"                                   =>"EAN",
            "---1"                                  =>"",
            "--2"                                   =>"Additional Attributes",
            "Shipping Rate"                         =>"Shipping Rate",
            "Original Price"                        =>"Original Price",
            "Coupon Code"                           =>"Coupon Code",
            "Coupon Code Description"               =>"Coupon Code Description",
            "Manufacturer"                          =>"Brand / Manufacturer",
            "Product Description"                   =>"Product Description",
            "Product Type"                          =>"Product Type",
            "Category"                              =>"Category",
            "Category ID"                           =>"Category ID",
            "Parent SKU"                            =>"Parent SKU",
            "Parent Name"                           =>"Parent Name",
            "Top Seller Rank"                       =>"Top Seller Rank",
            "Estimated Ship Date"                   =>"Estimated Ship Date",
            "Gender"                                =>"Gender",
            "Color"                                 =>"Color",
            "Material"                              =>"Material",
            "Size"                                  =>"Size",
            "Size Unit of Measure"                  =>"Size Unit of Measure",
            "Age Range"                             =>"Age Range",
            "Stock Description"                     =>"Stock Description",
            "Product Launch Date"                   =>"Product Launch Date",
            "Product Bullet Point 1"                =>"Product Bullet Point 1",
            "Product Bullet Point 2"                =>"Product Bullet Point 2",
            "Product Bullet Point 3"                =>"Product Bullet Point 3",
            "Product Bullet Point 4"                =>"Product Bullet Point 4",
            "Product Bullet Point 5"                =>"Product Bullet Point 5",
            "Alternative Image URL 1"               =>"Alternative Image URL 1",
            "Alternative Image URL 2"               =>"Alternative Image URL 2",
            "Alternative Image URL 3"               =>"Alternative Image URL 3",
            "Alternative Image URL 4"               =>"Alternative Image URL 4",
            "Alternative Image URL 5"               =>"Alternative Image URL 5",
            "Mobile URL"                            =>"Mobile URL",
            "Related Products"                      =>"Related Products",
            "Merchandising Type"                    =>"Merchandising Type",
            "Zip Code"                              =>"Zip Code",
            "Shipping Weight"                       =>"Shipping Weight",
            "Format"                                =>"Format",
            "Unit Price"                            =>"Unit Price",
            "Bundle"                                =>"Bundle",
            "Software Platform"                     =>"Software Platform",
            "Watch Display Type"                    =>"Watch Display Type",
            "Custom"                                =>"Custom",
            "---2"                                  =>"",
        );
        return $attributes;
    }

    public function shopmaniaAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "Category"                              =>"Category",
            "Manufacturer"                          =>"Manufacturer",
            "Model"                                 =>"Model",
            "MPC"                                   =>"Merchant Code",
            "Name"                                  =>"Product name",
            "Description"                           =>"Product description",
            "URL"                                   =>"Product URL",
            "Image"                                 =>"Image URL",
            "Price"                                 =>"Product price",
            "Currency"                              =>"Currency",
            "Shipping"                              =>"Shipping cost",
            "Availability"                          =>"Availability",
            "GTIN"                                  =>"GTIN",
            "---1"                                  =>"",

        );
        return $attributes;
    }

    public function bingAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "MerchantProductID"                     =>"MerchantProductID",
            "Title"                                 =>"Title",
            "ProductURL"                            =>"ProductURL",
            "Price"                                 =>"Price",
            "Description"                           =>"Description",
            "ImageURL"                              =>"ImageURL",
            "---1"                                  =>"",
            "--2"                                   =>"Recommended Attributes",
            "Brand"                                 =>"Brand",
            "MPN"                                   =>"MPN",
            "UPC"                                   =>"UPC",
            "ISBN"                                  =>"ISBN",
            "SKU"                                   =>"SKU",
            "Availability"                          =>"Availability",
            "Shipping"                              =>"Shipping",
            "MerchantCategory"                      =>"MerchantCategory",
            "B_Category"                            =>"B_Category",
            "ShippingWeight"                        =>"ShippingWeight",
            "Condition"                             =>"Condition",
            "Tax"                                   =>"Tax",
            "---2"                                  =>"",

        );
        return $attributes;
    }

    public function becomeAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "Unique ID"                             =>"Unique ID",
            "Title"                                 =>"Title",
            "Description"                           =>"Description",
            "Category"                              =>"Category",
            "Product URL"                           =>"Product URL",
            "Image URL"                             =>"Image URL",
            "Condition"                             =>"Condition",
            "Availability"                          =>"Availability",
            "Current Price"                         =>"Current Price",
            "---1"                                  =>"",
            "--2"                                   =>"Recommended Attributes",
            "Additional Image URL"                  =>"Additional Image URL",
            "Brand"                                 =>"Brand",
            "GTIN"                                  =>"GTIN",
            "MPN"                                   =>"MPN",
            "Ship Cost"                             =>"Ship Cost",
            "Ship Weight"                           =>"Ship Weight",
            "Bid"                                   =>"Bid",
            "Regular Price"                         =>"Regular Price",
            "Promo Text"                            =>"Promo Text",
            "Gender"                                =>"Gender",
            "Age Group"                             =>"Age Group",
            "Color"                                 =>"Color",
            "Size"                                  =>"Size",
            "Material"                              =>"Material",
            "Pattern"                               =>"Pattern",
            "Item Group ID"                         =>"Item Group ID",
            "---2"                                  =>"",
            "--3"                                   =>"Optional Attributes",
            "Page ID"                               =>"Page ID",
            "Page ID Variant"                       =>"Page ID Variant",
            "Generic Title"                         =>"Generic Title",
            "Unit Price"                            =>"Unit Price",
            "Currency"                              =>"Currency",
            "PZN"                                   =>"PZN",
            "Adult"                                 =>"Adult",
            "Delivery Period"                       =>"Delivery Period",
            "Energy Efficiency Class"               =>"Energy Efficiency Class",

            "---3"                                  =>"",
        );
        return $attributes;
    }

    public function connexityAttribute(){
        $attributes=array(
            "--1"                                   =>"Required Attributes",
            "Unique ID"                             =>"Unique ID",
            "Title"                                 =>"Title",
            "Description"                           =>"Description",
            "Category"                              =>"Category",
            "Product URL"                           =>"Product URL",
            "Image URL"                             =>"Image URL",
            "Condition"                             =>"Condition",
            "Availability"                          =>"Availability",
            "Current Price"                         =>"Current Price",
            "---1"                                  =>"",
            "--2"                                   =>"Recommended Attributes",
            "Brand"                                 =>"Brand",
            "GTIN"                                  =>"GTIN",
            "MPN"                                   =>"MPN",
            "Ship Cost"                             =>"Ship Cost",
            "Ship Weight"                           =>"Ship Weight",
            "Bid"                                   =>"Bid",
            "Regular Price"                         =>"Regular Price",
            "Promo Text"                            =>"Promo Text",
            "Gender"                                =>"Gender",
            "Age Group"                             =>"Age Group",
            "Color"                                 =>"Color",
            "Size"                                  =>"Size",
            "Material"                              =>"Material",
            "Pattern"                               =>"Pattern",
            "Item Group ID"                         =>"Item Group ID",
            "---2"                                  =>"",
            "--3"                                   =>"Optional Attributes",
            "Page ID"                               =>"Page ID",
            "Page ID Variant"                       =>"Page ID Variant",
            "Generic Title"                         =>"Generic Title",
            "Unit Price"                            =>"Unit Price",
            "Currency"                              =>"Currency",
            "PZN"                                   =>"PZN",
            "Adult"                                 =>"Adult",
            "Delivery Period"                       =>"Delivery Period",
            "Energy Efficiency Class"               =>"Energy Efficiency Class",
            "---3"                                  =>"",
        );
        return $attributes;
    }
}
